### ISSUE TITLE
EPIC: Frontend Framework 

### ISSUE THREAD

**Issue by MSevey** [mycodecareer/30daygroupproject#23]
There are a number of components that need to be set up for efficient development on the frontend React Application.

Here is a list:

- [x] #4 is needed to set the CSS framework for the applicaiton
- [x] #5 will be used for handling the multi page architecture 
- [ ] #10 will be needed as we build out the application as we will want to store the env vars securely
- [ ] #26
- [ ] #27
- [ ] #28
- [ ] #46
